# generate_structure.py — STRUCTURE.md を実ツリー・実シンボルから再生成する唯一の主体（契約: .guardrails/GUARDRAILS.md §7.4）
#
# 呼び出し（§7.1: 必ず uv 経由）:
#   uv run scripts/generate_structure.py           … 再生成して上書き。成功すれば差分の有無に関わらず exit 0
#   uv run scripts/generate_structure.py --check   … 書き込まない。最新なら exit 0、古ければ diff を stderr に出して exit 1
#   exit 2 = 内部エラー（git 不在・ルート解決失敗など）
#
# 保証（§7.4）:
#   - 原子的書き込み: 同一ディレクトリの一時ファイルに全出力 → os.replace() で置換
#   - 決定性: 同一ツリー ⇒ バイト一致（タイムスタンプ・絶対パス・環境情報を含めない）
#   - newline="\n" 明示（Windows で CRLF 化して鮮度チェックが偽陽性化するのを防ぐ — §7.2）
#
# 「古かったこと」の検知は pre-commit の「フックがファイルを変更したら失敗」機構に委ねる（§7.6）。

from __future__ import annotations

import argparse
import difflib
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import repo_scan as rs  # noqa: E402

BANNER = (
    "<!-- AUTOGENERATED by scripts/generate_structure.py — 手で編集しない。"
    "更新: uv run scripts/generate_structure.py -->"
)


def build_content(root: Path, files: list[str]) -> str:
    shown = [f for f in files if not rs.is_generated(f)]

    # 全ファイルはプロセス内で1回だけ読む（§7.3）
    texts: dict[str, str] = {}
    for rel in shown:
        ext = rs.ext_of(rel)
        if ext in rs.HEADER_REQUIRED_EXTS or ext in rs.CODE_EXTS:
            texts[rel] = rs.read_text(root, rel)

    lines = [BANNER, "", "# STRUCTURE.md — リポジトリ索引（自動生成・手編集禁止）", ""]

    # トップレベルディレクトリごとの節: パス + 役割一行（未記述は空欄のまま載せる — §7.4）
    groups: dict[str, list[str]] = {}
    for rel in shown:
        top = rel.split("/", 1)[0] if "/" in rel else "(root)"
        groups.setdefault(top, []).append(rel)
    for top in sorted(groups):
        lines.append("## " + ("ルート直下" if top == "(root)" else f"`{top}/`"))
        lines.append("")
        for rel in groups[top]:
            role = rs.role_header(rel, texts[rel]) if rel in texts else None
            lines.append(f"- `{rel}`" + (f" — {role}" if role else ""))
        lines.append("")

    # ファイルごとの公開シンボル一覧
    sym_sections = [
        (rel, syms)
        for rel in shown
        if rel in texts and (syms := rs.public_symbols(rel, texts[rel]))
    ]
    if sym_sections:
        lines.append("## 公開シンボル")
        lines.append("")
        for rel, syms in sym_sections:
            lines.append(f"### `{rel}`")
            lines.extend(f"- {s}" for s in syms)
            lines.append("")

    text = "\n".join(lines)
    return text if text.endswith("\n") else text + "\n"


def main(argv: list[str]) -> int:
    rs.reconfigure_stdio()
    parser = argparse.ArgumentParser(
        description="STRUCTURE.md の再生成（引数なし）/ 鮮度確認（--check）。契約: .guardrails/GUARDRAILS.md §7.4"
    )
    parser.add_argument("--check", action="store_true", help="書き込まず、古ければ diff を出して exit 1")
    args = parser.parse_args(argv)

    root = rs.repo_root()
    files = rs.list_tracked_files(root)
    content = build_content(root, files)
    target = root / "STRUCTURE.md"
    # CRLF 化などのバイト差も検出するため、universal newlines を通さず生バイトで読む
    current = target.read_bytes().decode("utf-8", "replace") if target.exists() else ""

    if args.check:
        if current == content:
            return 0
        sys.stderr.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile="STRUCTURE.md (現状)",
                tofile="STRUCTURE.md (最新)",
            )
        )
        print(
            "\nSTRUCTURE.md が古い。`uv run scripts/generate_structure.py` で再生成して"
            " `git add STRUCTURE.md` すること。",
            file=sys.stderr,
        )
        return 1

    # 原子的書き込み（§7.4: 途中で中断されても壊れた STRUCTURE.md を残さない）
    fd, tmp = tempfile.mkstemp(dir=str(root), prefix=".STRUCTURE.md.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        os.replace(tmp, target)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except rs.ScanError as exc:
        print(f"generate_structure: 内部エラー: {exc}", file=sys.stderr)
        sys.exit(2)
    except Exception as exc:  # 想定外も契約どおり exit 2 に倒す
        print(f"generate_structure: 内部エラー: {exc!r}", file=sys.stderr)
        sys.exit(2)
